spring:
   application:
    name: microsericers-zuul
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/text              # 数据库名称
    username: root
    password: root

server: 
  port: 9527
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: microsericers:9527
    prefer-ip-address: true 
 
 
zuul: 
  prefix: /micro
  ignored-services: "*"
  routes: 
    mydept.serviceId: MicroseriversApp
    mydept.path: /mydept/**
 
info:
  app.name: microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

